INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (1, 1);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (1, 3);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (1, 4);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (1, 5);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (1, 6);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (2, 2);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (2, 3);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (2, 4);
INSERT INTO wherefishing.place_fish (place_id, fish_id) VALUES (2, 7);